// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	bson "github.com/globalsign/mgo/bson"

	mock "github.com/stretchr/testify/mock"

	types "github.com/byteball/odex-backend/types"
)

// TokenDao is an autogenerated mock type for the TokenDao type
type TokenDao struct {
	mock.Mock
}

// Create provides a mock function with given fields: token
func (_m *TokenDao) Create(token *types.Token) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Drop provides a mock function with given fields:
func (_m *TokenDao) Drop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TokenDao) GetAll() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBaseTokens provides a mock function with given fields:
func (_m *TokenDao) GetBaseTokens() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAsset provides a mock function with given fields: asset
func (_m *TokenDao) GetByAsset(asset string) (*types.Token, error) {
	ret := _m.Called(asset)

	var r0 *types.Token
	if rf, ok := ret.Get(0).(func(string) *types.Token); ok {
		r0 = rf(asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAssetOrSymbol provides a mock function with given fields: assetOrSymbol
func (_m *TokenDao) GetByAssetOrSymbol(assetOrSymbol string) (*types.Token, error) {
	ret := _m.Called(assetOrSymbol)

	var r0 *types.Token
	if rf, ok := ret.Get(0).(func(string) *types.Token); ok {
		r0 = rf(assetOrSymbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(assetOrSymbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TokenDao) GetByID(id bson.ObjectId) (*types.Token, error) {
	ret := _m.Called(id)

	var r0 *types.Token
	if rf, ok := ret.Get(0).(func(bson.ObjectId) *types.Token); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bson.ObjectId) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySymbol provides a mock function with given fields: symbol
func (_m *TokenDao) GetBySymbol(symbol string) (*types.Token, error) {
	ret := _m.Called(symbol)

	var r0 *types.Token
	if rf, ok := ret.Get(0).(func(string) *types.Token); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListedBaseTokens provides a mock function with given fields:
func (_m *TokenDao) GetListedBaseTokens() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListedTokens provides a mock function with given fields:
func (_m *TokenDao) GetListedTokens() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuoteTokens provides a mock function with given fields:
func (_m *TokenDao) GetQuoteTokens() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnlistedTokens provides a mock function with given fields:
func (_m *TokenDao) GetUnlistedTokens() ([]types.Token, error) {
	ret := _m.Called()

	var r0 []types.Token
	if rf, ok := ret.Get(0).(func() []types.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
